# Import Libraries

In [1]:
import cv2 as cv
import numpy as np
import matplotlib.pyplot as plt

# Read/load Imput image

In [2]:
input_image = cv.imread("..\data\images.jpeg")
cv.imshow("Original Image", input_image)

# Matrix of ones which is multipled by a scaler value of 60, matrix has dimesions same as out input image
Intensity_Matrix = np.ones(input_image.shape, dtype = 'uint8') * 60

# Print Intensity Matrix
print(Intensity_Matrix)

# Add Intensity Matrix to input image in order to increase the brightness
brightened_image = cv.add(input_image, Intensity_Matrix)
cv.imshow("Bright", input_image)

# Subtract Intensity Matrix from input image in order to decrease the brightness
darkended_image = cv.subtract(input_image, Intensity_Matrix)
cv.imshow("Dark", input_image)

cv.waitKey(0)
cv.destroyAllWindows()

[[[60 60 60]
  [60 60 60]
  [60 60 60]
  ...
  [60 60 60]
  [60 60 60]
  [60 60 60]]

 [[60 60 60]
  [60 60 60]
  [60 60 60]
  ...
  [60 60 60]
  [60 60 60]
  [60 60 60]]

 [[60 60 60]
  [60 60 60]
  [60 60 60]
  ...
  [60 60 60]
  [60 60 60]
  [60 60 60]]

 ...

 [[60 60 60]
  [60 60 60]
  [60 60 60]
  ...
  [60 60 60]
  [60 60 60]
  [60 60 60]]

 [[60 60 60]
  [60 60 60]
  [60 60 60]
  ...
  [60 60 60]
  [60 60 60]
  [60 60 60]]

 [[60 60 60]
  [60 60 60]
  [60 60 60]
  ...
  [60 60 60]
  [60 60 60]
  [60 60 60]]]
